name: random_color_picker
dependencies:
  modular:
    path: ../../../dart-packages/modular
  representation_types:
    path: ../../representation_types
modular:
  targets:
    - output_name: random_color_picker.mojo
      entry_point: lib/main.dart
