name: cloud_indexer
version: 0.0.0
description: Provides an endpoint for changes in the Modular cloud storage.
dependencies:
  appengine: '^0.3.0'
  archive: any
  logging: any
  mime: any
  mockito: any
  parser:
    path: ../../../parser
  shelf: any
  test: any
