name: cloud_indexer
version: 0.0.0
description: Provides an endpoint for changes in the Modular cloud storage.
dependencies:
  appengine: '^0.3.0'
  args: any
  archive: any
  cloud_indexer_common:
    path: ../common
  logging: any
  mime: any
  mockito: any
  parser:
    path: ../../deps/parser
  shelf: any
  test: any
