name: modular_core
version: 0.2.6
description: SDK for building for the Modular platform.
author: Modular Authors <modular-hackers@google.com>
homepage: https://github.com/domokit/modular/tree/master/public
dependencies:
  parser:
    path: ../../parser # TODO: roll this in to this package
  collection: any
  logging: ">=0.11.1 <0.12.0"
  uuid: any
dev_dependencies:
  test: ^0.12.11
