name: modular_flutter
version: 0.2.6
description: SDK for building for the Modular platform using Dart and Flutter.
author: Modular Authors <modular-hackers@google.com>
homepage: https://github.com/domokit/modular/tree/master/public
dependencies:
  # The `modular configure` command is responsible for generating this symlink.
  # This means that `modular configure` must be run before running `pub get` in
  # this directory.
  flutter:
    path: lib/cache/.flutter_root/packages/flutter
  modular:
    path: ../modular
