name: modular_tools
version: 0.0.1
description: Tools for building Modular applications.
dev_dependencies:
  archive: any
  args: any
  file_utils: any
  logging: any
  mojom: any
  path: any
  semaphore: any
  yaml: any
