name: synced_store
dependencies:
  modular_services:
    path: ../modular_services
dev_dependencies:
  modular:
    path: ../dart-packages/modular
  mojo_apptest: any
modular:
  targets:
    - output_name: mock_synced_store.mojo
      entry_point: lib/mock/main.dart
