name: ledger
dependencies:
  modular_services:
    path: ../modular_services
  synced_store:
    path: ../synced_store
dev_dependencies:
  modular:
    path: ../dart-packages/modular
  mojo_apptest: any
modular:
  targets:
    - output_name: ledger.mojo
      entry_point: lib/main.dart
    - output_name: ledger_test.mojo
      entry_point: apptest/main.dart
