name: modular
version: 0.2.6
description: SDK for building for the Modular platform using Dart.
author: Modular Authors <modular-hackers@google.com>
homepage: https://github.com/domokit/modular/tree/master/public
dependencies:
  modular_core:
    path: ../modular_core
  mojo: any

dev_dependencies:
  mojo_apptest: any
modular:
  targets:
    - output_name: public_api_test.mojo
      entry_point: apptest/main.dart
