name: notification_handler
version: 0.0.0
description: Handles manifest file changes from the Modular CDN.
dependencies:
  appengine: '^0.3.0'
  cloud_indexer_common:
    path: ../common
  http: any
  indexer_pipeline:
    path: ../../../indexer/pipeline
  logging: any
  mockito: any
  parser:
    path: ../../../parser
  path: any
  shelf: any
  test: any
