name: color_displayer
dependencies:
  modular_flutter:
    path: ../../../dart-packages/modular_flutter
  representation_types:
    path: ../../representation_types
modular:
  project_type: flutter
  targets:
    - output_name: color_displayer.flx
      entry_point: lib/main.dart
