name: suggestinator
dependencies:
  collection: any
  common:
    path: ../common/dart
  handler:
    path: ../handler
  indexer_client:
    path: ../indexer/client
  modular:
    path: ../dart-packages/modular
  modular_services:
    path: ../modular_services
  parser:
    path: ../parser
dev_dependencies:
  test: ^0.12.11
modular:
  root: ..
  targets:
    - output_name: suggestinator.mojo
      entry_point: mojo/main.dart
